/*
 * Copyright (c) 2023 Arkadi Shishlov
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

// -----------------------------------------------------
// NOTE: THIS HEADER IS ALSO INCLUDED BY ASSEMBLER SO
//       SHOULD ONLY CONSIST OF PREPROCESSOR DIRECTIVES
// -----------------------------------------------------

#ifndef _BOARDS_LILYGO_T_DISPLAY_RP2040_GENERIC_I2S_H
#define _BOARDS_LILYGO_T_DISPLAY_RP2040_GENERIC_I2S_H

#define LILYGO_T_DISPLAY_RP2040
#define GENERIC_I2S

#define GENERIC_I2S_DIN_PIN 9
#define GENERIC_I2S_BCK_PIN 10
#define GENERIC_I2S_LRCK_PIN 11

#ifndef PICO_AUDIO_I2S_DATA_PIN
#define PICO_AUDIO_I2S_DATA_PIN GENERIC_I2S_DIN_PIN
#endif
#ifndef PICO_AUDIO_I2S_CLOCK_PIN_BASE
#define PICO_AUDIO_I2S_CLOCK_PIN_BASE GENERIC_I2S_BCK_PIN
#endif

// LilyGo T-Display RP2040
#define LILYGO_T_DISPLAY_RP2040_BUTTON_IO6_PIN 6
#define LILYGO_T_DISPLAY_RP2040_BUTTON_IO7_PIN 7

#define LILYGO_T_DISPLAY_RP2040_LED_PIN 25
#ifndef PICO_DEFAULT_LED_PIN
#define PICO_DEFAULT_LED_PIN LILYGO_T_DISPLAY_RP2040_LED_PIN
#endif

#define LILYGO_T_DISPLAY_RP2040_MIPI_DISPLAY_SPI_CLOCK_SPEED_HZ 65000000
#define LILYGO_T_DISPLAY_RP2040_MIPI_DISPLAY_SPI_PORT spi0
#define LILYGO_T_DISPLAY_RP2040_MIPI_DISPLAY_PIN_CS   5
#define LILYGO_T_DISPLAY_RP2040_MIPI_DISPLAY_PIN_DC   1
#define LILYGO_T_DISPLAY_RP2040_MIPI_DISPLAY_PIN_PWR  22
#define LILYGO_T_DISPLAY_RP2040_MIPI_DISPLAY_PIN_RST  0
#define LILYGO_T_DISPLAY_RP2040_MIPI_DISPLAY_PIN_BL   4
#define LILYGO_T_DISPLAY_RP2040_MIPI_DISPLAY_PIN_CLK  2
#define LILYGO_T_DISPLAY_RP2040_MIPI_DISPLAY_PIN_MOSI 3
#define LILYGO_T_DISPLAY_RP2040_MIPI_DISPLAY_PIN_MISO -1
#define LILYGO_T_DISPLAY_RP2040_MIPI_DISPLAY_PIXEL_FORMAT MIPI_DCS_PIXEL_FORMAT_16BIT // MIPI_DCS_* are hagl_hal defs
#define LILYGO_T_DISPLAY_RP2040_MIPI_DISPLAY_ADDRESS_MODE MIPI_DCS_ADDRESS_MODE_RGB|MIPI_DCS_ADDRESS_MODE_SWAP_XY|MIPI_DCS_ADDRESS_MODE_MIRROR_Y // landscape, USB connector on the left
// true dimensions
//#define LILYGO_T_DISPLAY_RP2040_MIPI_DISPLAY_WIDTH  240
//#define LILYGO_T_DISPLAY_RP2040_MIPI_DISPLAY_HEIGHT 135
//#define LILYGO_T_DISPLAY_RP2040_MIPI_DISPLAY_OFFSET_X 40
//#define LILYGO_T_DISPLAY_RP2040_MIPI_DISPLAY_OFFSET_Y 52
// Doom-aligned viewport
#define LILYGO_T_DISPLAY_RP2040_MIPI_DISPLAY_WIDTH  320
#define LILYGO_T_DISPLAY_RP2040_MIPI_DISPLAY_HEIGHT 200
#define LILYGO_T_DISPLAY_RP2040_MIPI_DISPLAY_OFFSET_X 0
#define LILYGO_T_DISPLAY_RP2040_MIPI_DISPLAY_OFFSET_Y 30

// for MIPI HAGL HAL
#ifndef MIPI_DISPLAY_SPI_CLOCK_SPEED_HZ
#define MIPI_DISPLAY_SPI_CLOCK_SPEED_HZ LILYGO_T_DISPLAY_RP2040_MIPI_DISPLAY_SPI_CLOCK_SPEED_HZ
#endif
#ifndef MIPI_DISPLAY_SPI_PORT
#define MIPI_DISPLAY_SPI_PORT LILYGO_T_DISPLAY_RP2040_MIPI_DISPLAY_SPI_PORT
#endif
#ifndef MIPI_DISPLAY_PIN_CS
#define MIPI_DISPLAY_PIN_CS LILYGO_T_DISPLAY_RP2040_MIPI_DISPLAY_PIN_CS
#endif
#ifndef MIPI_DISPLAY_PIN_DC
#define MIPI_DISPLAY_PIN_DC LILYGO_T_DISPLAY_RP2040_MIPI_DISPLAY_PIN_DC
#endif
#ifndef MIPI_DISPLAY_PIN_PWR
#define MIPI_DISPLAY_PIN_PWR LILYGO_T_DISPLAY_RP2040_MIPI_DISPLAY_PIN_PWR
#endif
#ifndef MIPI_DISPLAY_PIN_RST
#define MIPI_DISPLAY_PIN_RST LILYGO_T_DISPLAY_RP2040_MIPI_DISPLAY_PIN_RST
#endif
#ifndef MIPI_DISPLAY_PIN_BL
#define MIPI_DISPLAY_PIN_BL LILYGO_T_DISPLAY_RP2040_MIPI_DISPLAY_PIN_BL
#endif
#ifndef MIPI_DISPLAY_PIN_CLK
#define MIPI_DISPLAY_PIN_CLK LILYGO_T_DISPLAY_RP2040_MIPI_DISPLAY_PIN_CLK
#endif
#ifndef MIPI_DISPLAY_PIN_MOSI
#define MIPI_DISPLAY_PIN_MOSI LILYGO_T_DISPLAY_RP2040_MIPI_DISPLAY_PIN_MOSI
#endif
#ifndef MIPI_DISPLAY_PIN_MISO
#define MIPI_DISPLAY_PIN_MISO LILYGO_T_DISPLAY_RP2040_MIPI_DISPLAY_PIN_MISO
#endif

#ifndef MIPI_DISPLAY_PIXEL_FORMAT
#define MIPI_DISPLAY_PIXEL_FORMAT LILYGO_T_DISPLAY_RP2040_MIPI_DISPLAY_PIXEL_FORMAT
#endif
#ifndef MIPI_DISPLAY_ADDRESS_MODE
#define MIPI_DISPLAY_ADDRESS_MODE LILYGO_T_DISPLAY_RP2040_MIPI_DISPLAY_ADDRESS_MODE
#endif
#ifndef MIPI_DISPLAY_WIDTH
#define MIPI_DISPLAY_WIDTH LILYGO_T_DISPLAY_RP2040_MIPI_DISPLAY_WIDTH
#endif
#ifndef MIPI_DISPLAY_HEIGHT
#define MIPI_DISPLAY_HEIGHT LILYGO_T_DISPLAY_RP2040_MIPI_DISPLAY_HEIGHT
#endif
#ifndef MIPI_DISPLAY_OFFSET_X
#define MIPI_DISPLAY_OFFSET_X LILYGO_T_DISPLAY_RP2040_MIPI_DISPLAY_OFFSET_X
#endif
#ifndef MIPI_DISPLAY_OFFSET_Y
#define MIPI_DISPLAY_OFFSET_Y LILYGO_T_DISPLAY_RP2040_MIPI_DISPLAY_OFFSET_Y
#endif

// pico-sdk/src/boards/include/boards/pico.h

#define PICO_BOOT_STAGE2_CHOOSE_W25Q080 1

#ifndef PICO_FLASH_SPI_CLKDIV
#define PICO_FLASH_SPI_CLKDIV 2
#endif

#ifndef PICO_FLASH_SIZE_BYTES
#define PICO_FLASH_SIZE_BYTES (4 * 1024 * 1024)
#endif

// pico net
#ifndef PICO_DEFAULT_I2C
#define PICO_DEFAULT_I2C 0
#endif
#ifndef PICO_DEFAULT_I2C_SDA_PIN
#define PICO_DEFAULT_I2C_SDA_PIN 12
#endif
#ifndef PICO_DEFAULT_I2C_SCL_PIN
#define PICO_DEFAULT_I2C_SCL_PIN 13
#endif

#endif
