/*
 * Copyright (c) 2022 Arkadi Shishlov
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

// -----------------------------------------------------
// NOTE: THIS HEADER IS ALSO INCLUDED BY ASSEMBLER SO
//       SHOULD ONLY CONSIST OF PREPROCESSOR DIRECTIVES
// -----------------------------------------------------

#ifndef _BOARDS_PIMORONI_DISPLAY_2_AUDIO_PACK_H
#define _BOARDS_PIMORONI_DISPLAY_2_AUDIO_PACK_H

// Audio Pack
#define PIMORONI_DISPLAY_2_PACK
#define PIMORONI_AUDIO_PACK

#define PIMORONI_AUDIO_PACK_I2S_DIN_PIN 9
#define PIMORONI_AUDIO_PACK_I2S_BCK_PIN 10
#define PIMORONI_AUDIO_PACK_I2S_LRCK_PIN 11

#ifndef PICO_AUDIO_I2S_DATA_PIN
#define PICO_AUDIO_I2S_DATA_PIN PIMORONI_AUDIO_PACK_I2S_DIN_PIN
#endif
#ifndef PICO_AUDIO_I2S_CLOCK_PIN_BASE
#define PICO_AUDIO_I2S_CLOCK_PIN_BASE PIMORONI_AUDIO_PACK_I2S_BCK_PIN
#endif

// Display 2 Pack
#define PIMORONI_DISPLAY_2_PACK_BUTTON_A_PIN 12
#define PIMORONI_DISPLAY_2_PACK_BUTTON_B_PIN 13
#define PIMORONI_DISPLAY_2_PACK_BUTTON_X_PIN 14
#define PIMORONI_DISPLAY_2_PACK_BUTTON_Y_PIN 15

#define PIMORONI_DISPLAY_2_PACK_LED_R_PIN 6
#define PIMORONI_DISPLAY_2_PACK_LED_G_PIN 7
#define PIMORONI_DISPLAY_2_PACK_LED_B_PIN 8
#ifndef PICO_DEFAULT_LED_PIN
#define PICO_DEFAULT_LED_PIN PIMORONI_DISPLAY_2_PACK_LED_G_PIN
#endif

#define PIMORONI_DISPLAY_2_PACK_MIPI_DISPLAY_SPI_CLOCK_SPEED_HZ 62500000
#define PIMORONI_DISPLAY_2_PACK_MIPI_DISPLAY_SPI_PORT spi0
#define PIMORONI_DISPLAY_2_PACK_MIPI_DISPLAY_PIN_CS   17
#define PIMORONI_DISPLAY_2_PACK_MIPI_DISPLAY_PIN_DC   16
#define PIMORONI_DISPLAY_2_PACK_MIPI_DISPLAY_PIN_PWR  -1
#define PIMORONI_DISPLAY_2_PACK_MIPI_DISPLAY_PIN_RST  -1
#define PIMORONI_DISPLAY_2_PACK_MIPI_DISPLAY_PIN_BL   20
#define PIMORONI_DISPLAY_2_PACK_MIPI_DISPLAY_PIN_CLK  18
#define PIMORONI_DISPLAY_2_PACK_MIPI_DISPLAY_PIN_MOSI 19
#define PIMORONI_DISPLAY_2_PACK_MIPI_DISPLAY_PIN_MISO -1
#define PIMORONI_DISPLAY_2_PACK_MIPI_DISPLAY_PIXEL_FORMAT MIPI_DCS_PIXEL_FORMAT_16BIT // MIPI_DCS_* are hagl_hal defs
#define PIMORONI_DISPLAY_2_PACK_MIPI_DISPLAY_ADDRESS_MODE MIPI_DCS_ADDRESS_MODE_RGB|MIPI_DCS_ADDRESS_MODE_SWAP_XY|MIPI_DCS_ADDRESS_MODE_MIRROR_X // landscape, button labels upright
#define PIMORONI_DISPLAY_2_PACK_MIPI_DISPLAY_WIDTH  320
#define PIMORONI_DISPLAY_2_PACK_MIPI_DISPLAY_HEIGHT 240
#define PIMORONI_DISPLAY_2_PACK_MIPI_DISPLAY_OFFSET_X 0
#define PIMORONI_DISPLAY_2_PACK_MIPI_DISPLAY_OFFSET_Y 0

// for MIPI HAGL HAL
#ifndef MIPI_DISPLAY_SPI_CLOCK_SPEED_HZ
#define MIPI_DISPLAY_SPI_CLOCK_SPEED_HZ PIMORONI_DISPLAY_2_PACK_MIPI_DISPLAY_SPI_CLOCK_SPEED_HZ
#endif
#ifndef MIPI_DISPLAY_SPI_PORT
#define MIPI_DISPLAY_SPI_PORT PIMORONI_DISPLAY_2_PACK_MIPI_DISPLAY_SPI_PORT
#endif
#ifndef MIPI_DISPLAY_PIN_CS
#define MIPI_DISPLAY_PIN_CS PIMORONI_DISPLAY_2_PACK_MIPI_DISPLAY_PIN_CS
#endif
#ifndef MIPI_DISPLAY_PIN_DC
#define MIPI_DISPLAY_PIN_DC PIMORONI_DISPLAY_2_PACK_MIPI_DISPLAY_PIN_DC
#endif
#ifndef MIPI_DISPLAY_PIN_PWR
#define MIPI_DISPLAY_PIN_PWR PIMORONI_DISPLAY_2_PACK_MIPI_DISPLAY_PIN_PWR
#endif
#ifndef MIPI_DISPLAY_PIN_RST
#define MIPI_DISPLAY_PIN_RST PIMORONI_DISPLAY_2_PACK_MIPI_DISPLAY_PIN_RST
#endif
#ifndef MIPI_DISPLAY_PIN_BL
#define MIPI_DISPLAY_PIN_BL PIMORONI_DISPLAY_2_PACK_MIPI_DISPLAY_PIN_BL
#endif
#ifndef MIPI_DISPLAY_PIN_CLK
#define MIPI_DISPLAY_PIN_CLK PIMORONI_DISPLAY_2_PACK_MIPI_DISPLAY_PIN_CLK
#endif
#ifndef MIPI_DISPLAY_PIN_MOSI
#define MIPI_DISPLAY_PIN_MOSI PIMORONI_DISPLAY_2_PACK_MIPI_DISPLAY_PIN_MOSI
#endif
#ifndef MIPI_DISPLAY_PIN_MISO
#define MIPI_DISPLAY_PIN_MISO PIMORONI_DISPLAY_2_PACK_MIPI_DISPLAY_PIN_MISO
#endif

#ifndef MIPI_DISPLAY_PIXEL_FORMAT
#define MIPI_DISPLAY_PIXEL_FORMAT PIMORONI_DISPLAY_2_PACK_MIPI_DISPLAY_PIXEL_FORMAT
#endif
#ifndef MIPI_DISPLAY_ADDRESS_MODE
#define MIPI_DISPLAY_ADDRESS_MODE PIMORONI_DISPLAY_2_PACK_MIPI_DISPLAY_ADDRESS_MODE
#endif
#ifndef MIPI_DISPLAY_WIDTH
#define MIPI_DISPLAY_WIDTH PIMORONI_DISPLAY_2_PACK_MIPI_DISPLAY_WIDTH
#endif
#ifndef MIPI_DISPLAY_HEIGHT
#define MIPI_DISPLAY_HEIGHT PIMORONI_DISPLAY_2_PACK_MIPI_DISPLAY_HEIGHT
#endif
#ifndef MIPI_DISPLAY_OFFSET_X
#define MIPI_DISPLAY_OFFSET_X PIMORONI_DISPLAY_2_PACK_MIPI_DISPLAY_OFFSET_X
#endif
#ifndef MIPI_DISPLAY_OFFSET_Y
#define MIPI_DISPLAY_OFFSET_Y PIMORONI_DISPLAY_2_PACK_MIPI_DISPLAY_OFFSET_Y
#endif

// Pimoroni Display 2 Pack + Audio Pack + Pico Omnibus expander have a Pico with them,
// so default anything we haven't set above
#include "boards/pico.h" // pico-sdk/src/boards/include/boards/pico.h

#endif
